### ISSUE TITLE
See if users can run the conus404_explore notebook on ESIP qhub 0.4

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-python/hytest-development#1]
@thodson-usgs , can you please see if you can run this notebook on https://jupyter.data.science.earth and report back with any issues? 

It should work with the 'users/pangeo' environment there:
https://github.com/USGS-python/hytest-development/blob/main/gallery/conus404_explore.ipynb

**Comment by rsignell-usgs** [comment]
Ah yes!  You will need AWS credentials to access a requester-pays bucket.    Open a terminal in JupyterLab and do:
```
conda activate pangeo
aws configure --profile esip-qhub
```
and you will be asked four questions to set up your profile. 
I'll give you the answers offline.

**Comment by thodson-usgs** [comment]
That fixed it.
Everything ran without error, though
```python
%%time
da = ds.T2.isel(y=600,x=600).load()
```
was very slow to execute
```
CPU times: user 1.5 s, sys: 162 ms, total: 1.67 s
Wall time: 1min 20s
```
Better on second run
```
CPU times: user 940 ms, sys: 77 ms, total: 1.02 s
Wall time: 13.2 s
```

**Comment by rsignell-usgs** [comment]
@thodson-usgs probably all the workers hadn't kicked in when you did the first run.  For benchmarking, we can change the options in the cluster startup to :  `wait_for_cluster=True`.      Let me know if you test my theory.  :)

**Comment by rsignell-usgs** [comment]
Closing this since you successfully tested.  Thanks @thodson-usgs !
