### ISSUE TITLE
Test out new on-prem 500TB drive 

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-python/hytest-development#5]
Jeff Falgout has installed the 500TB drive and would like to make sure it meets HyTEST needs!

How about this for a plan:
* find out how to access the drive (contact Jeff Falgout)
* copy the 40TB CONUS404 derived zarr dataset from it's current location on caldera to the drive.  
* add the copy of the dataset on the 500GB drive to the intake catalog. 
* run the CONUS explore notebook on it, using a local dask cluster on Denali, calculating the mean temperature over a year, and compare performance of the existing location and the new location

See the CONUS404 explorer notebook in this repo for intake catalog location, which then points to the existing location on calderaa

That should be a good start!

**Comment by rsignell-usgs** [comment]
@ashalper-usgs , Roland suggested this would be a good task for you to chew on!

**Comment by rsignell-usgs** [comment]
@pnorton-usgs pointed out on the nhgf call that the disk lives on /caldera/hytest_scratch:

```
pangeo) [rsignell@ml-0001 hytest_scratch]$ df -h
Filesystem                                     Size  Used Avail Use% Mounted on
devtmpfs                                       189G     0  189G   0% /dev
tmpfs                                          189G  387M  188G   1% /run
tmpfs                                          339G   12G  328G   4% /
tmpfs                                          189G  1.2M  189G   1% /dev/shm
tmpfs                                          189G     0  189G   0% /sys/fs/cgroup
master:/cm/shared                              1.9T  449G  1.4T  25% /cm/shared
172.22.0.67@o2ib:172.22.0.68@o2ib:/cls01052    225T  6.1T  216T   3% /home
172.22.0.73@o2ib:172.22.0.74@o2ib:/cls01048    2.2P  1.8P  383T  83% /caldera/projects
tmpfs                                           38G     0   38G   0% /run/user/87414
172.22.0.110@o2ib:172.22.0.111@o2ib:/calpav01  443T  5.9M  421T   1% /caldera/hytest_scratch
```

**Comment by ashalper-usgs** [comment]
@rsignell-usgs, what is the current location of the CONUS404 derived zarr dataset?

**Comment by pnorton-usgs** [comment]
@ashalper-usgs 
The daily is at:
`/caldera/projects/usgs/water/wbeep/conus404_work/zarr_daily_out`

The hourly is at:
`/caldera/projects/usgs/water/wbeep/conus404_work/zarr_out/conus404_hourly.zarr`

**Comment by rviger-usgs** [comment]
Thanks for banging on this, folks! Excited to put this resource into use!

**Comment by rviger-usgs** [comment]
From prelim benchmarking from Jeff Falgout:

[6/17 1:57 PM] Falgout, Jeff T
So - I've been benchmarking this thing today and, depending on settings I use, come up with the following Max Write: 21521.15 MiB/sec (22566.56 MB/sec)
Max Read: 12108.60 MiB/sec (12696.79 MB/sec)

[6/17 1:58 PM] Falgout, Jeff T
It's somewhat variable depending on file size being written and read, but around 20GB/s peak write and 12-14GB/s peak read is where I'm at.

**Comment by ashalper-usgs** [comment]
rsync of `/caldera/projects/usgs/water/wbeep/conus404_work/zarr_daily_out` finished this morning, but rsync of `/caldera/projects/usgs/water/wbeep/conus404_work/zarr_out/conus404_hourly.zarr` is still running (started ~24 hrs. ago).

**Comment by ashalper-usgs** [comment]
I think this finally completed (I wasn't around for the end of the `zarr_out` rsync). Hope this looks correct:

```
[ashalper@tg-dtn2 conus404] du -hs zarr_daily_out/
1.6T    zarr_daily_out/
[ashalper@tg-dtn2 conus404] du -hs zarr_out
14T     zarr_out
```

**Comment by rviger-usgs** [comment]
is there a status on this? are we expecting any finish date/data? I'd like to report back to Falgout that all is good. I'd also like to move forward on a plan to utilizing this, as well as announcing this progress.

**Comment by pnorton-usgs** [comment]
@ashalper-usgs - the hourly zarr_out apparently did not successfully finish. The final size of the directory should be about 40T.

**Comment by rsignell-usgs** [comment]
We had a hiccup when we tried to run a cluster on tallgrass writing to /caldera/hytest-scratch, because the tallgrass compute nodes were not seeing the disk.     Jeff Falgout was notified and fixed it in a matter of minutes!   He said it was just that they forgot to make the settings used during testing permanent.   (e.g. it should not happen again).
